fix: docker compose

diff --git a/deployments/compose/docker-compose.yml b/deployments/compose/docker-compose.yml
--- a/deployments/compose/docker-compose.yml
+++ b/deployments/compose/docker-compose.yml
@@ -18,15 +18,21 @@ services:
       "
       pd --version &&
       if ! test -e /pd/network_data/node0/cometbft/config/config.toml ; then
-          >&2 printf 'WARN: network config not found. Creating fresh node identity.'
-          >&2 echo ' See docs for details: https://guide.penumbra.zone/node/pd/join-network.html
-          /bin/pd network --network-dir /pd/network_data join
+          >&2 printf 'WARN: network config not found. Creating fresh local network.\n'
+          rm -rf /pd/network_data &&
+          /bin/pd network --network-dir /pd/network_data generate
       else
           >&2 echo 'Node config already found, using it'
       fi &&
-      chown 100 -R /pd/network_data/node0/cometbft &&
-      chown 1000 -R /pd/network_data/node0/pd &&
-      ls -l /pd/network_data/node0/ && exit 0
+      if test -d /pd/network_data/node0 ; then
+          mkdir -p /pd/network_data/node0/cometbft/data &&
+          chown 100 -R /pd/network_data/node0/cometbft &&
+          chown 1000 -R /pd/network_data/node0/pd &&
+          ls -l /pd/network_data/node0/ && exit 0
+      else
+          >&2 echo 'ERROR: network generation failed'
+          exit 1
+      fi
       "
     restart: on-failure
     volumes:
@@ -49,6 +55,7 @@ services:
     volumes:
       - penumbra-pd-node0:/pd
     user: "${UID:-1000}"
+    stop_signal: SIGKILL
     depends_on:
       - pd-node0-init
     ports:
@@ -63,6 +70,7 @@ services:
       - "26657:26657"
     volumes:
       - penumbra-pd-node0:/cometbft
+    user: "100"
     environment:
       CMTHOME: /cometbft/network_data/node0/cometbft
     command: start --proxy_app=tcp://pd-node0:26658
